/// Flutter icons RadioApp
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  RadioApp
///      fonts:
///       - asset: fonts/RadioApp.ttf
///
///
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
/// * MFG Labs, Copyright (C) 2012 by Daniel Bruce
///         Author:    MFG Labs
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.mfglabs.com/
///
// ignore_for_file: constant_identifier_names

library;

import 'package:flutter/widgets.dart';

class RadioAppIcon {
  RadioAppIcon._();

  static const _kFontFam = 'RadioApp';
  static const String? _kFontPkg = null;

  static const IconData instagram_square =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData twitter_square =
      IconData(0xf081, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData facebook_square =
      IconData(0xf082, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData soundcloud =
      IconData(0xf089, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData twitter =
      IconData(0xf099, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData facebook_1 =
      IconData(0xf09a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData instagram_1 =
      IconData(0xf16d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData whatsapp =
      IconData(0xf232, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData snapchat =
      IconData(0xf2ab, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData snapchat_ghost =
      IconData(0xf2ac, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData telegram =
      IconData(0xf2c6, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData facebook_f =
      IconData(0xf39e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData facebook_messenger =
      IconData(0xf39f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData telegram_plane =
      IconData(0xf3fe, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData whatsapp_square =
      IconData(0xf40c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
